/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cunori.views;

import java.awt.Color;

/**
 *
 * @author ferna
 */
public class GUI extends javax.swing.JFrame {

    private Color colorEnteredPerfil; 
    private Color colorExitedPerfil; 
    
    public GUI() {
        this.setSize(1000, 650);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        colorEnteredPerfil = new Color(0,87,95);
        colorExitedPerfil = new Color(0,109,119);
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        lbPerfil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pBody = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(500, 500));

        pMenu.setBackground(new java.awt.Color(0, 109, 119));
        pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPerfil.setBackground(new java.awt.Color(0, 109, 119));
        lbPerfil.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lbPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerfil.setText("PERFIL");
        lbPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPerfil.setOpaque(true);
        lbPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPerfilMouseExited(evt);
            }
        });
        pMenu.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 58));
        pMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 10));

        getContentPane().add(pMenu, java.awt.BorderLayout.LINE_START);

        pBody.setBackground(new java.awt.Color(237, 246, 249));
        pBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        pBody.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 296, -1, -1));

        jLabel2.setBackground(new java.awt.Color(69, 123, 157));
        jLabel2.setText("jLabel2");
        pBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 186, 37, -1));

        getContentPane().add(pBody, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPerfilMouseEntered
        lbPerfil.setBackground(colorEnteredPerfil);
    }//GEN-LAST:event_lbPerfilMouseEntered

    private void lbPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPerfilMouseExited
        lbPerfil.setBackground(colorExitedPerfil);
    }//GEN-LAST:event_lbPerfilMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JPanel pBody;
    private javax.swing.JPanel pMenu;
    // End of variables declaration//GEN-END:variables
}
