/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cunori.views;

import com.cunori.controllers.FacturaJpaController;
import com.cunori.models.Factura;
import com.cunori.models.Reservacion;
import com.cunori.xml.GenerarXml;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class PanelFacturas extends javax.swing.JPanel {

    private Color colorEnteredMenu;
    private Color colorExitedMenu;

    private EntityManagerFactory emf;
    private FacturaJpaController facturaJpaController;

    private DefaultTableModel modelTbFacturas;
    private DefaultTableModel modelTbReservaciones;

    private SimpleDateFormat formatoFechaDMA;
    private SimpleDateFormat formatoFechaAMD;

    private Factura facturaSeleccionada;
    private Collection<Reservacion> reservaciones;

    private GenerarXml generarXml;

    public PanelFacturas() {
        initComponents();

        colorEnteredMenu = new Color(0, 87, 95);
        colorExitedMenu = new Color(0, 109, 119);

        modelTbFacturas = (DefaultTableModel) tbFacturas.getModel();
        modelTbFacturas.setRowCount(0);
        modelTbReservaciones = (DefaultTableModel) tbReservaciones.getModel();
        modelTbReservaciones.setRowCount(0);

        reservaciones = new ArrayList<>();

        formatoFechaDMA = new SimpleDateFormat("dd/MM/yyyy");
        formatoFechaAMD = new SimpleDateFormat("yyyy/MM/yyyy");

        generarXml = new GenerarXml();

        try {
            emf = Persistence.createEntityManagerFactory("com.cunori.hotel.estrella.real_hotel-estrella-real_jar_1.0-SNAPSHOTPU");
            facturaJpaController = new FacturaJpaController(emf);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        lbFacturar = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservaciones = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        lbSeleccionar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFacturas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel22.setText("Realiza Facturación");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(237, 246, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 87, 95));
        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel7.setText("Buscar por");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        cmbBuscar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todos" }));
        jPanel1.add(cmbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(237, 246, 249));
        txtBuscar.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txtBuscar.setBorder(null);
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 260, -1));

        lbFacturar.setBackground(new java.awt.Color(0, 109, 119));
        lbFacturar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbFacturar.setForeground(new java.awt.Color(255, 255, 255));
        lbFacturar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFacturar.setText("Facturar");
        lbFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbFacturar.setEnabled(false);
        lbFacturar.setOpaque(true);
        lbFacturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbFacturarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbFacturarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbFacturarMousePressed(evt);
            }
        });
        jPanel1.add(lbFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 520, 120, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 260, 20));

        tbReservaciones.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tbReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Habitación", "Tipo", "Registro", "Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbReservaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 350, 380));

        jLabel12.setBackground(new java.awt.Color(0, 87, 95));
        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel12.setText("Reservaciones");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 210, 30));

        jLabel13.setBackground(new java.awt.Color(0, 87, 95));
        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel13.setText("Facturas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 30));

        lbBuscar.setBackground(new java.awt.Color(0, 109, 119));
        lbBuscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lbBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBuscar.setText("Buscar");
        lbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBuscar.setOpaque(true);
        lbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbBuscarMousePressed(evt);
            }
        });
        jPanel1.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 80, 30));

        lbSeleccionar.setBackground(new java.awt.Color(0, 109, 119));
        lbSeleccionar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        lbSeleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSeleccionar.setText("Seleccionar");
        lbSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSeleccionar.setOpaque(true);
        lbSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSeleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSeleccionarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbSeleccionarMousePressed(evt);
            }
        });
        jPanel1.add(lbSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 120, 30));

        tbFacturas.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        tbFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Factura", "Nit", "Nombre", "Apellido(s)", "Reservaciones", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbFacturas);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 590, 300));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1160, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void lbFacturarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFacturarMouseEntered
        lbFacturar.setBackground(colorEnteredMenu);
    }//GEN-LAST:event_lbFacturarMouseEntered

    private void lbFacturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFacturarMouseExited
        lbFacturar.setBackground(colorExitedMenu);
    }//GEN-LAST:event_lbFacturarMouseExited

    private void lbFacturarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFacturarMousePressed
        if (reservaciones.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una factura.", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        generarXml.setNombreDocumento("certificacion");
        ZonedDateTime fechaActual = ZonedDateTime.now();
        DateTimeFormatter formatoISO = DateTimeFormatter.ISO_OFFSET_DATE_TIME;
        generarXml.setFechaEmision(fechaActual.format(formatoISO));
        generarXml.setCorreoReceptor("receptor@gmail.com");
        generarXml.setNitReceptor(facturaSeleccionada.getNitCliente().getNitCliente());
        generarXml.setNombreReceptor(facturaSeleccionada.getNitCliente().getNombre());
        generarXml.setDireccionReceptor("CIUDAD");
        generarXml.setCodigoPostalReceptor("20001");
        generarXml.setMunicipioReceptor("CHIQUIMULA");
        generarXml.setDepartamentoReceptor("CHIQUIMULA");
        int cantidad = reservaciones.size();
        generarXml.setCantidadItems(cantidad);
        String[] descripcion = new String[cantidad];
        String[] precioUnitarioItem = new String[cantidad];
        String[] montoIvaItem = new String[cantidad];
        String[] montoInguat = new String[cantidad];
        String[] montoGravable = new String[cantidad];
        String[] totalItem = new String[cantidad];
        String totalImpuestoIVA;
        String totalImpuestoITH;
        String granTotal;
        
        /*int i = 0;
        for (Reservacion r : reservaciones) {
            descripcion[i] = "Habitación " + r.getNumeroHabitacion().getIdTipoHabitacion().getNombre() + ", " 
                    +  r.getCamasExtras() + " camas extras.";
            precioUnitarioItem[i] = 
            i +=1;
        }*/
        
    }//GEN-LAST:event_lbFacturarMousePressed

    private void lbBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBuscarMouseEntered

    private void lbBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbBuscarMouseExited

    private void lbBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBuscarMousePressed
        List<Factura> facturas = facturaJpaController.findFacturaEntities();
        modelTbFacturas.setRowCount(0);
        for (Factura factura : facturas) {
            Object[] nuevaFila = {factura.getIdFactura(), factura.getNitCliente().getNitCliente(), factura.getNitCliente().getNombre(),
                factura.getNitCliente().getApellidos(), factura.getReservacionCollection().size(), formatoFechaDMA.format(factura.getFechaCreacion()), factura.getTotal().toString()};
            modelTbFacturas.addRow(nuevaFila);
        }

    }//GEN-LAST:event_lbBuscarMousePressed

    private void lbSeleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeleccionarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSeleccionarMouseEntered

    private void lbSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeleccionarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSeleccionarMouseExited

    private void lbSeleccionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSeleccionarMousePressed
        if (tbFacturas.getSelectedRow() == -1 || tbFacturas.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una factura.", "Error de seleccion.", JOptionPane.ERROR_MESSAGE);
            return;
        }

        facturaSeleccionada = facturaJpaController.findFactura((Integer) tbFacturas.getValueAt(tbFacturas.getSelectedRow(), 0));
        reservaciones = facturaSeleccionada.getReservacionCollection();

        modelTbReservaciones.setRowCount(0);
        for (Reservacion reservacion : reservaciones) {
            Object[] nuevaReserva = {reservacion.getNumeroHabitacion().getNumeroHabitacion(), reservacion.getNumeroHabitacion().getIdTipoHabitacion().getNombre(),
                formatoFechaDMA.format(reservacion.getCheckIn()), formatoFechaDMA.format(reservacion.getCheckOut())};
            modelTbReservaciones.addRow(nuevaReserva);
        }
    }//GEN-LAST:event_lbSeleccionarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbFacturar;
    private javax.swing.JLabel lbSeleccionar;
    private javax.swing.JTable tbFacturas;
    private javax.swing.JTable tbReservaciones;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
