/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cunori.views;

import com.cunori.controllers.TipoHabitacionJpaController;
import com.cunori.models.TipoHabitacion;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ferna
 */
public class PanelReservaciones extends javax.swing.JPanel {

    private Color colorEnteredMenu; 
    private Color colorExitedMenu; 
    
    private DefaultComboBoxModel modelCmbTipoHabitacion;
    
    private EntityManagerFactory emf;
    
    TipoHabitacionJpaController tipoHabitacionEntityManager;
    private List<TipoHabitacion> tiposHabitacion;
    
    public PanelReservaciones() {
        initComponents();
        
        colorEnteredMenu = new Color(0,87,95);
        colorExitedMenu = new Color(0,109,119);
        
        try {
            emf = Persistence.createEntityManagerFactory("com.cunori.hotel.estrella.real_hotel-estrella-real_jar_1.0-SNAPSHOTPU");
            tipoHabitacionEntityManager = new TipoHabitacionJpaController(emf);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
        
        initPanelReservaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNuevaReservacion = new javax.swing.JPanel();
        lbBuscarHabitacionReservacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHabitaciones = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoHabitacion = new javax.swing.JComboBox<>();
        lbGuardarCambios2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dcSalida = new com.toedter.calendar.JDateChooser();
        dcRegistro = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHabitaciones1 = new javax.swing.JTable();
        lbGuardarCambios3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreUsuario1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        lbGuardarCambios4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pNuevaReservacion.setBackground(new java.awt.Color(237, 246, 249));
        pNuevaReservacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBuscarHabitacionReservacion.setBackground(new java.awt.Color(0, 109, 119));
        lbBuscarHabitacionReservacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbBuscarHabitacionReservacion.setForeground(new java.awt.Color(255, 255, 255));
        lbBuscarHabitacionReservacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBuscarHabitacionReservacion.setText("Buscar");
        lbBuscarHabitacionReservacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBuscarHabitacionReservacion.setOpaque(true);
        lbBuscarHabitacionReservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbBuscarHabitacionReservacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbBuscarHabitacionReservacionMouseExited(evt);
            }
        });
        pNuevaReservacion.add(lbBuscarHabitacionReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, 30));

        tbHabitaciones.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        tbHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Tipo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbHabitaciones);

        pNuevaReservacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 400, 240));

        jLabel9.setBackground(new java.awt.Color(0, 87, 95));
        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel9.setText("Salida *");
        pNuevaReservacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 210, 30));

        cmbTipoHabitacion.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        pNuevaReservacion.add(cmbTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 290, 40));

        lbGuardarCambios2.setBackground(new java.awt.Color(0, 109, 119));
        lbGuardarCambios2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbGuardarCambios2.setForeground(new java.awt.Color(255, 255, 255));
        lbGuardarCambios2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGuardarCambios2.setText("Confirmar Reservación");
        lbGuardarCambios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGuardarCambios2.setOpaque(true);
        lbGuardarCambios2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbGuardarCambios2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbGuardarCambios2MouseExited(evt);
            }
        });
        pNuevaReservacion.add(lbGuardarCambios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 210, 30));

        jLabel11.setBackground(new java.awt.Color(0, 87, 95));
        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel11.setText("Tipo de habitación *");
        pNuevaReservacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 30));

        jLabel12.setBackground(new java.awt.Color(0, 87, 95));
        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel12.setText("Registro *");
        pNuevaReservacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        dcSalida.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        pNuevaReservacion.add(dcSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 210, 30));

        dcRegistro.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        pNuevaReservacion.add(dcRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 30));

        jLabel13.setBackground(new java.awt.Color(0, 87, 95));
        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel13.setText("Reservaciones Agregadas");
        pNuevaReservacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 270, -1));

        tbHabitaciones1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        tbHabitaciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Habitación", "Tipo", "Precio", "Camas extra", "Registro", "Salida", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tbHabitaciones1);

        pNuevaReservacion.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 510, 240));

        lbGuardarCambios3.setBackground(new java.awt.Color(0, 109, 119));
        lbGuardarCambios3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbGuardarCambios3.setForeground(new java.awt.Color(255, 255, 255));
        lbGuardarCambios3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGuardarCambios3.setText("Añadir");
        lbGuardarCambios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGuardarCambios3.setOpaque(true);
        lbGuardarCambios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbGuardarCambios3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbGuardarCambios3MouseExited(evt);
            }
        });
        pNuevaReservacion.add(lbGuardarCambios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 80, 30));

        jLabel14.setBackground(new java.awt.Color(0, 87, 95));
        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel14.setText("Habitaciones disponibles ");
        pNuevaReservacion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, -1));

        txtNombreUsuario1.setBackground(new java.awt.Color(237, 246, 249));
        txtNombreUsuario1.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txtNombreUsuario1.setText("Q 0.00");
        txtNombreUsuario1.setBorder(null);
        txtNombreUsuario1.setEnabled(false);
        pNuevaReservacion.add(txtNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 230, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        pNuevaReservacion.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 230, 10));

        jLabel15.setBackground(new java.awt.Color(0, 87, 95));
        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        jLabel15.setText("Total *");
        pNuevaReservacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 160, -1));

        lbGuardarCambios4.setBackground(new java.awt.Color(0, 109, 119));
        lbGuardarCambios4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbGuardarCambios4.setForeground(new java.awt.Color(255, 255, 255));
        lbGuardarCambios4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGuardarCambios4.setText("Borrar");
        lbGuardarCambios4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGuardarCambios4.setOpaque(true);
        lbGuardarCambios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbGuardarCambios4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbGuardarCambios4MouseExited(evt);
            }
        });
        pNuevaReservacion.add(lbGuardarCambios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 80, 30));

        add(pNuevaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1220, 570));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel21.setText("Nueva Reservación");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void initPanelReservaciones(){
        modelCmbTipoHabitacion = (DefaultComboBoxModel) cmbTipoHabitacion.getModel();
        tiposHabitacion = tipoHabitacionEntityManager.findTipoHabitacionEntities();
        
        for (TipoHabitacion tipoHabitacion : tiposHabitacion) {
            modelCmbTipoHabitacion.addElement(tipoHabitacion);
        }
        
    }
    
    
    private void lbBuscarHabitacionReservacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBuscarHabitacionReservacionMouseEntered
        lbBuscarHabitacionReservacion.setBackground(colorEnteredMenu);
    }//GEN-LAST:event_lbBuscarHabitacionReservacionMouseEntered

    private void lbBuscarHabitacionReservacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBuscarHabitacionReservacionMouseExited
        lbBuscarHabitacionReservacion.setBackground(colorExitedMenu);
    }//GEN-LAST:event_lbBuscarHabitacionReservacionMouseExited

    private void lbGuardarCambios2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios2MouseEntered
        lbGuardarCambios2.setBackground(colorEnteredMenu);
    }//GEN-LAST:event_lbGuardarCambios2MouseEntered

    private void lbGuardarCambios2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios2MouseExited
        lbGuardarCambios2.setBackground(colorExitedMenu);
    }//GEN-LAST:event_lbGuardarCambios2MouseExited

    private void lbGuardarCambios3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios3MouseEntered
        lbGuardarCambios3.setBackground(colorEnteredMenu);
    }//GEN-LAST:event_lbGuardarCambios3MouseEntered

    private void lbGuardarCambios3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios3MouseExited
        lbGuardarCambios3.setBackground(colorExitedMenu);
    }//GEN-LAST:event_lbGuardarCambios3MouseExited

    private void lbGuardarCambios4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbGuardarCambios4MouseEntered

    private void lbGuardarCambios4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGuardarCambios4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbGuardarCambios4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipoHabitacion;
    private com.toedter.calendar.JDateChooser dcRegistro;
    private com.toedter.calendar.JDateChooser dcSalida;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbBuscarHabitacionReservacion;
    private javax.swing.JLabel lbGuardarCambios2;
    private javax.swing.JLabel lbGuardarCambios3;
    private javax.swing.JLabel lbGuardarCambios4;
    private javax.swing.JPanel pNuevaReservacion;
    private javax.swing.JTable tbHabitaciones;
    private javax.swing.JTable tbHabitaciones1;
    private javax.swing.JTextField txtNombreUsuario1;
    // End of variables declaration//GEN-END:variables
}
